// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cv
List cv(NumericVector y, NumericMatrix x, NumericVector lambda, NumericMatrix initialvals, int n, int k, int p, int d, bool profile, bool mu, bool g, double fixed_g, bool scad, double theta_upper, double theta_lower, bool penalty, int ncores);
RcppExport SEXP _GPpenalty_cv(SEXP ySEXP, SEXP xSEXP, SEXP lambdaSEXP, SEXP initialvalsSEXP, SEXP nSEXP, SEXP kSEXP, SEXP pSEXP, SEXP dSEXP, SEXP profileSEXP, SEXP muSEXP, SEXP gSEXP, SEXP fixed_gSEXP, SEXP scadSEXP, SEXP theta_upperSEXP, SEXP theta_lowerSEXP, SEXP penaltySEXP, SEXP ncoresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type initialvals(initialvalsSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< bool >::type profile(profileSEXP);
    Rcpp::traits::input_parameter< bool >::type mu(muSEXP);
    Rcpp::traits::input_parameter< bool >::type g(gSEXP);
    Rcpp::traits::input_parameter< double >::type fixed_g(fixed_gSEXP);
    Rcpp::traits::input_parameter< bool >::type scad(scadSEXP);
    Rcpp::traits::input_parameter< double >::type theta_upper(theta_upperSEXP);
    Rcpp::traits::input_parameter< double >::type theta_lower(theta_lowerSEXP);
    Rcpp::traits::input_parameter< bool >::type penalty(penaltySEXP);
    Rcpp::traits::input_parameter< int >::type ncores(ncoresSEXP);
    rcpp_result_gen = Rcpp::wrap(cv(y, x, lambda, initialvals, n, k, p, d, profile, mu, g, fixed_g, scad, theta_upper, theta_lower, penalty, ncores));
    return rcpp_result_gen;
END_RCPP
}
// kernel_exp
NumericMatrix kernel_exp(const NumericMatrix& x1, const NumericMatrix& x2, const NumericVector& theta, double g);
RcppExport SEXP _GPpenalty_kernel_exp(SEXP x1SEXP, SEXP x2SEXP, SEXP thetaSEXP, SEXP gSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type x2(x2SEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type g(gSEXP);
    rcpp_result_gen = Rcpp::wrap(kernel_exp(x1, x2, theta, g));
    return rcpp_result_gen;
END_RCPP
}
// eucli_dist
NumericMatrix eucli_dist(const NumericMatrix& x1, const NumericMatrix& x2);
RcppExport SEXP _GPpenalty_eucli_dist(SEXP x1SEXP, SEXP x2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type x2(x2SEXP);
    rcpp_result_gen = Rcpp::wrap(eucli_dist(x1, x2));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_GPpenalty_cv", (DL_FUNC) &_GPpenalty_cv, 17},
    {"_GPpenalty_kernel_exp", (DL_FUNC) &_GPpenalty_kernel_exp, 4},
    {"_GPpenalty_eucli_dist", (DL_FUNC) &_GPpenalty_eucli_dist, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_GPpenalty(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
