# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cv <- function(y, x, lambda, initialvals, n = -1L, k = -1L, p = -1L, d = -1L, profile = TRUE, mu = FALSE, g = FALSE, fixed_g = -1, scad = FALSE, theta_upper = 1000, theta_lower = 0.001, penalty = TRUE, ncores = 1L) {
    .Call(`_GPpenalty_cv`, y, x, lambda, initialvals, n, k, p, d, profile, mu, g, fixed_g, scad, theta_upper, theta_lower, penalty, ncores)
}

kernel_exp <- function(x1, x2, theta, g) {
    .Call(`_GPpenalty_kernel_exp`, x1, x2, theta, g)
}

eucli_dist <- function(x1, x2) {
    .Call(`_GPpenalty_eucli_dist`, x1, x2)
}

