# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cv <- function(y, x, lambda, initialvals, n = -1L, k = -1L, p = -1L, dim = -1L, profile = TRUE, mu = FALSE, g = FALSE, fixed_g = -1, scad = FALSE, penalty = TRUE, ncores = 1L) {
    .Call(`_GPpenalty_cv`, y, x, lambda, initialvals, n, k, p, dim, profile, mu, g, fixed_g, scad, penalty, ncores)
}

